name: Deploy Lambda Function

on:
  push:
    branches:
      - master  # Change if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install AWS CLI
        run: |
          sudo apt update
          sudo apt install -y curl unzip
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install
          aws --version  # Verify installation

      - name: Install Dependencies
        run: |
          cd server  # Move to server folder
          npm ci  # Install dependencies
          ls -lh node_modules  # Check if installed

      - name: Zip Lambda Function
        run: |
          cd server  # Move to server folder
          zip -r ../function.zip .  # Zip everything inside ./server
          ls -lh ../function.zip  # Check zip file size

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code \
            --function-name myLambdaFunction \  # Change this
            --zip-file fileb://function.zip
