name: Deploy Lambda Function

on:
  push:
    branches:
      - master  # Change if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update AWS CLI
        run: |
          sudo /usr/local/aws-cli/v2/current/bin/aws --version || true  # Check current version
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip -o awscliv2.zip
          sudo ./aws/install --update
          aws --version  # Verify updated version

      - name: Install Dependencies
        run: |
          cd server  # Move to server folder
          npm ci  # Install dependencies
          ls -lh node_modules  # Check if installed

      - name: Zip Lambda Function
        run: |
          cd server  # Move to server folder
          zip -r ../function.zip .  # Zip everything inside ./server
          ls -lh ../function.zip  # Check zip file size
          
      - name: Debug AWS Credentials
        run: aws sts get-caller-identity

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code \
            --function-name myLambdaFunction \  # Change this to your actual function name
            --zip-file fileb://function.zip
