name: Deploy Lambda Function

on:
  push:
    branches:
      - master  # Change to your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Change to your AWS region

      - name: Zip Lambda Function
        run: zip -r function.zip index.js node_modules  # Modify for your language

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code \
            --function-name myLambdaFunction \  # Change to your Lambda function name
            --zip-file fileb://function.zip
